// AI-GENERATED FILE
// Generated by Claude (Anthropic AI coding assistant), 2026-08-24, for the MSc IT+
// Build & Test phase of the Gymora project.
//
// Unit tests for ProtectedRoute.jsx. useAuth() is mocked directly rather than
// going through a real login flow, so each test can control isLoggedIn precisely
// and check exactly one behaviour: render the protected content, or redirect.

import { render, screen } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { describe, expect, it, vi } from 'vitest'
import ProtectedRoute from './ProtectedRoute.jsx'
import { useAuth } from '../context/AuthContext.jsx'

vi.mock('../context/AuthContext.jsx', () => ({
  useAuth: vi.fn(),
}))

function renderWithRouter(initialPath = '/protected') {
  return render(
    <MemoryRouter initialEntries={[initialPath]}>
      <Routes>
        <Route path="/login" element={<div>Login Page</div>} />
        <Route
          path="/protected"
          element={
            <ProtectedRoute>
              <div>Secret Content</div>
            </ProtectedRoute>
          }
        />
      </Routes>
    </MemoryRouter>
  )
}

describe('ProtectedRoute', () => {
  it('renders the wrapped page when the user is logged in', () => {
    useAuth.mockReturnValue({ isLoggedIn: true })

    renderWithRouter()

    expect(screen.getByText('Secret Content')).toBeInTheDocument()
  })

  it('redirects to /login when the user is not logged in', () => {
    useAuth.mockReturnValue({ isLoggedIn: false })

    renderWithRouter()

    expect(screen.getByText('Login Page')).toBeInTheDocument()
    expect(screen.queryByText('Secret Content')).not.toBeInTheDocument()
  })
})
