"""
AI-GENERATED FILE
Generated by Claude (Anthropic AI coding assistant), 2026-08-24, for the MSc IT+
Build & Test phase of the Gymora project.

Shared pytest fixtures for the backend test suite:
- forces safe, fake settings (JWT secret, Groq key, DB creds) so tests never touch
  the real database or the real Groq API, regardless of what's in backend/.env
- swaps the real Postgres connection for an isolated in-memory SQLite database,
  rebuilt fresh for every single test function
- wires that database into a FastAPI TestClient via dependency_overrides, so
  requests made through `client` hit the real routers/schemas/validation but a
  throwaway database
- provides small reusable fixtures (a saved user, an auth header, a sample
  exercise/muscle group) so individual test files stay short
"""

import os

# Must happen before `app.config`/`app.database` are imported anywhere below,
# since Settings() is validated at import time and env vars win over a real .env.
os.environ["DB_USER"] = "test_user"
os.environ["DB_PASSWORD"] = "test_password"
os.environ["DB_HOST"] = "localhost"
os.environ["DB_NAME"] = "gymora_test"
os.environ["JWT_SECRET_KEY"] = "test-secret-key-not-for-production-use"
os.environ["GROQ_API_KEY"] = "test-groq-key-not-a-real-key"

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.core.security import create_access_token, hash_password
from app.database import Base, get_db
from app.main import app
from app.models.equipment import Equipment
from app.models.exercise import Exercise
from app.models.exercise_equipment import ExerciseEquipment
from app.models.exercise_muscle_group import ExerciseMuscleGroup
from app.models.muscle_group import MuscleGroup
from app.models.user import User

# StaticPool keeps every connection pointing at the SAME in-memory database.
# Without it, SQLite's ":memory:" database would disappear as soon as the
# session that created it closed the connection.
test_engine = create_engine(
    "sqlite:///:memory:",
    connect_args={"check_same_thread": False},
    poolclass=StaticPool,
)
TestSessionLocal = sessionmaker(bind=test_engine, autoflush=False, autocommit=False)


@pytest.fixture()
def db_session():
    """A fresh, empty database for a single test."""
    Base.metadata.create_all(bind=test_engine)
    session = TestSessionLocal()
    try:
        yield session
    finally:
        session.close()
        Base.metadata.drop_all(bind=test_engine)


@pytest.fixture()
def client(db_session):
    """A FastAPI TestClient whose get_db dependency points at db_session."""

    def override_get_db():
        yield db_session

    app.dependency_overrides[get_db] = override_get_db
    with TestClient(app) as test_client:
        yield test_client
    app.dependency_overrides.clear()


@pytest.fixture()
def test_user(db_session):
    """A saved user with a known password, for login/ownership tests."""
    user = User(
        username="testuser",
        email="test@example.com",
        password_hash=hash_password("Password123!"),
    )
    db_session.add(user)
    db_session.commit()
    db_session.refresh(user)
    return user


@pytest.fixture()
def other_user(db_session):
    """A second, separate user — used to prove one user can't see another's data."""
    user = User(
        username="otheruser",
        email="other@example.com",
        password_hash=hash_password("Password123!"),
    )
    db_session.add(user)
    db_session.commit()
    db_session.refresh(user)
    return user


@pytest.fixture()
def auth_headers(test_user):
    token = create_access_token(user_id=test_user.user_id)
    return {"Authorization": f"Bearer {token}"}


@pytest.fixture()
def other_auth_headers(other_user):
    token = create_access_token(user_id=other_user.user_id)
    return {"Authorization": f"Bearer {token}"}


@pytest.fixture()
def sample_exercise(db_session):
    """One realistic exercise row, for tests that log/reference an exercise."""
    exercise = Exercise(
        name="Barbell Bench Press",
        description="Compound chest press performed lying on a flat bench.",
        difficulty_level="beginner",
        is_active=True,
    )
    db_session.add(exercise)
    db_session.commit()
    db_session.refresh(exercise)
    return exercise


@pytest.fixture()
def exercise_library(db_session):
    """
    A small but realistic exercise library covering several muscle groups,
    used by the routine-generator tests (app/services/routine_generator.py
    needs real muscle group / equipment / exercise rows to have anything to pick from).
    """
    muscle_names = ["Chest", "Back", "Shoulders", "Quadriceps", "Core"]
    muscle_groups = {}
    for name in muscle_names:
        group = MuscleGroup(name=name)
        db_session.add(group)
        muscle_groups[name] = group
    db_session.flush()

    barbell = Equipment(name="Barbell")
    dumbbell = Equipment(name="Dumbbell")
    db_session.add_all([barbell, dumbbell])
    db_session.flush()

    exercises = []
    definitions = [
        ("Barbell Bench Press", "Chest", barbell, "beginner"),
        ("Dumbbell Fly", "Chest", dumbbell, "intermediate"),
        ("Barbell Row", "Back", barbell, "beginner"),
        ("Lat Pulldown", "Back", None, "beginner"),
        ("Overhead Press", "Shoulders", barbell, "intermediate"),
        ("Barbell Squat", "Quadriceps", barbell, "beginner"),
        ("Dumbbell Lunge", "Quadriceps", dumbbell, "beginner"),
        ("Plank", "Core", None, "beginner"),
    ]

    for name, muscle_name, equipment, difficulty in definitions:
        exercise = Exercise(name=name, difficulty_level=difficulty, is_active=True)
        db_session.add(exercise)
        db_session.flush()

        db_session.add(
            ExerciseMuscleGroup(
                exercise_id=exercise.exercise_id,
                muscle_group_id=muscle_groups[muscle_name].muscle_group_id,
                is_primary=True,
            )
        )

        if equipment is not None:
            db_session.add(
                ExerciseEquipment(
                    exercise_id=exercise.exercise_id,
                    equipment_id=equipment.equipment_id,
                )
            )

        exercises.append(exercise)

    db_session.commit()
    return {
        "muscle_groups": muscle_groups,
        "equipment": {"Barbell": barbell, "Dumbbell": dumbbell},
        "exercises": exercises,
    }
