"""
AI-GENERATED FILE
Generated by Claude (Anthropic AI coding assistant), 2026-08-24, for the MSc IT+
Build & Test phase of the Gymora project.

Integration tests for app/routers/auth.py: register, login, and /auth/me,
run through a real FastAPI TestClient against an isolated in-memory database
(see conftest.py). These exercise the full request/response cycle — routing,
Pydantic validation, password hashing, JWT issuance — not just isolated functions.
"""


def test_register_creates_user(client):
    response = client.post(
        "/auth/register",
        json={"username": "newuser", "email": "New@Example.com", "password": "Password123!"},
    )

    assert response.status_code == 201
    body = response.json()
    assert body["email"] == "new@example.com"  # normalised to lowercase
    assert body["username"] == "newuser"
    assert "password" not in body
    assert "password_hash" not in body


def test_register_duplicate_email_is_rejected(client):
    payload = {"username": "userone", "email": "dupe@example.com", "password": "Password123!"}
    client.post("/auth/register", json=payload)

    second = client.post(
        "/auth/register",
        json={"username": "usertwo", "email": "dupe@example.com", "password": "Password123!"},
    )

    assert second.status_code == 400
    assert "already registered" in second.json()["detail"]


def test_register_duplicate_email_is_case_insensitive(client):
    client.post(
        "/auth/register",
        json={"username": "userone", "email": "Case@Example.com", "password": "Password123!"},
    )

    second = client.post(
        "/auth/register",
        json={"username": "usertwo", "email": "case@example.com", "password": "Password123!"},
    )

    assert second.status_code == 400


def test_login_with_correct_credentials_returns_token(client, test_user):
    response = client.post(
        "/auth/login",
        json={"email": "test@example.com", "password": "Password123!"},
    )

    assert response.status_code == 200
    body = response.json()
    assert body["token_type"] == "bearer"
    assert len(body["access_token"]) > 0


def test_login_with_wrong_password_is_rejected(client, test_user):
    response = client.post(
        "/auth/login",
        json={"email": "test@example.com", "password": "wrong-password"},
    )

    assert response.status_code == 401
    # Message must not reveal which field (email vs password) was wrong.
    assert response.json()["detail"] == "Incorrect email or password"


def test_login_with_unknown_email_is_rejected(client):
    response = client.post(
        "/auth/login",
        json={"email": "ghost@example.com", "password": "Password123!"},
    )

    assert response.status_code == 401
    assert response.json()["detail"] == "Incorrect email or password"


def test_read_current_user_without_token_is_rejected(client):
    response = client.get("/auth/me")
    assert response.status_code == 401


def test_read_current_user_with_invalid_token_is_rejected(client):
    response = client.get("/auth/me", headers={"Authorization": "Bearer not-a-real-token"})
    assert response.status_code == 401


def test_read_current_user_with_valid_token_returns_profile(client, test_user, auth_headers):
    response = client.get("/auth/me", headers=auth_headers)

    assert response.status_code == 200
    body = response.json()
    assert body["user_id"] == test_user.user_id
    assert body["email"] == "test@example.com"
