"""
AI-GENERATED FILE
Generated by Claude (Anthropic AI coding assistant), 2026-08-24, for the MSc IT+
Build & Test phase of the Gymora project.

Integration tests for app/routers/routine.py: /routines/generate (rules engine +
LLM explanation), saving, listing, and ownership isolation.

The LLM call (ask_llm) is patched out everywhere here — this suite is testing the
routine *routes*, not the third-party Groq API, and hitting the real API in every
test run would be slow, flaky, and burn API quota. This mirrors the "test harness"
approach from the MSc IT+ slides: swap the real external call for a local double.
"""

from unittest.mock import patch

from app.services.llm import LLMError


def test_generate_requires_auth(client):
    response = client.post(
        "/routines/generate",
        json={
            "goal": "strength",
            "experience_level": "beginner",
            "days_per_week": 3,
            "session_length_minutes": 45,
        },
    )
    assert response.status_code == 401


def test_generate_with_no_matching_exercises_returns_400(client, auth_headers):
    # No exercise_library fixture used here on purpose: an empty database
    # means the rules engine has nothing to pick from.
    with patch("app.routers.routine.ask_llm", return_value="explanation"):
        response = client.post(
            "/routines/generate",
            headers=auth_headers,
            json={
                "goal": "strength",
                "experience_level": "beginner",
                "days_per_week": 3,
                "session_length_minutes": 45,
            },
        )

    assert response.status_code == 400
    assert "Not enough exercises" in response.json()["detail"]


def test_generate_returns_routine_with_llm_explanation(client, auth_headers, exercise_library):
    with patch("app.routers.routine.ask_llm", return_value="Here is why this plan suits you.") as mock_ask:
        response = client.post(
            "/routines/generate",
            headers=auth_headers,
            json={
                "goal": "muscle gain",
                "experience_level": "beginner",
                "days_per_week": 3,
                "session_length_minutes": 45,
                "equipment": [],
            },
        )

    assert response.status_code == 200
    body = response.json()
    assert len(body["exercises"]) > 0
    assert body["explanation"] == "Here is why this plan suits you."
    mock_ask.assert_called_once()


def test_generate_still_returns_routine_when_llm_is_down(client, auth_headers, exercise_library):
    # The router is written so an LLM outage degrades gracefully: the rules-based
    # routine is still perfectly usable even with no explanation text.
    with patch("app.routers.routine.ask_llm", side_effect=LLMError("service unavailable")):
        response = client.post(
            "/routines/generate",
            headers=auth_headers,
            json={
                "goal": "strength",
                "experience_level": "beginner",
                "days_per_week": 3,
                "session_length_minutes": 45,
            },
        )

    assert response.status_code == 200
    body = response.json()
    assert len(body["exercises"]) > 0
    assert body["explanation"] is None


def test_generate_does_not_save_anything(client, auth_headers, exercise_library):
    with patch("app.routers.routine.ask_llm", return_value="explanation"):
        client.post(
            "/routines/generate",
            headers=auth_headers,
            json={
                "goal": "strength",
                "experience_level": "beginner",
                "days_per_week": 3,
                "session_length_minutes": 45,
            },
        )

    list_response = client.get("/routines/", headers=auth_headers)
    assert list_response.json() == []


def _build_saveable_routine(exercises):
    return {
        "name": "My push/pull/legs",
        "goal": "strength",
        "experience_level": "beginner",
        "days_per_week": 3,
        "session_length_minutes": 45,
        "exercises": [
            {"exercise_id": exercises[0].exercise_id, "day_number": 1, "exercise_order": 1, "suggested_sets": 3}
        ],
    }


def test_save_routine_persists_it(client, auth_headers, exercise_library):
    payload = _build_saveable_routine(exercise_library["exercises"])
    response = client.post("/routines/", headers=auth_headers, json=payload)

    assert response.status_code == 201
    body = response.json()
    assert body["is_saved"] is True
    assert len(body["exercises"]) == 1


def test_list_routines_orders_newest_first(client, db_session, auth_headers, exercise_library):
    from datetime import datetime, timedelta, timezone

    from app.models.routine import Routine

    payload = _build_saveable_routine(exercise_library["exercises"])

    first = client.post("/routines/", headers=auth_headers, json={**payload, "name": "First"}).json()
    second = client.post("/routines/", headers=auth_headers, json={**payload, "name": "Second"}).json()

    # SQLite's server_default=func.now() only has second-level resolution, so two
    # inserts in the same test can tie on created_at. Postgres (the real backend)
    # doesn't have this problem, so timestamps are set explicitly here to make the
    # ordering assertion deterministic rather than dependent on real-clock timing.
    now = datetime.now(timezone.utc)
    db_session.get(Routine, first["routine_id"]).created_at = now - timedelta(minutes=1)
    db_session.get(Routine, second["routine_id"]).created_at = now
    db_session.commit()

    response = client.get("/routines/", headers=auth_headers)
    names = [row["name"] for row in response.json()]
    assert names == ["Second", "First"]


def test_get_other_users_routine_returns_404(client, auth_headers, other_auth_headers, exercise_library):
    payload = _build_saveable_routine(exercise_library["exercises"])
    created = client.post("/routines/", headers=other_auth_headers, json=payload).json()

    response = client.get(f"/routines/{created['routine_id']}", headers=auth_headers)
    assert response.status_code == 404


def test_delete_routine_removes_it(client, auth_headers, exercise_library):
    payload = _build_saveable_routine(exercise_library["exercises"])
    created = client.post("/routines/", headers=auth_headers, json=payload).json()

    delete_response = client.delete(f"/routines/{created['routine_id']}", headers=auth_headers)
    assert delete_response.status_code == 204

    get_response = client.get(f"/routines/{created['routine_id']}", headers=auth_headers)
    assert get_response.status_code == 404
