"""
AI-GENERATED FILE
Generated by Claude (Anthropic AI coding assistant), 2026-08-24, for the MSc IT+
Build & Test phase of the Gymora project.

Integration tests for app/routers/assistant.py — the RAG-style fitness assistant.
ask_llm() is patched out here too (see test_llm_service.py for the direct test
harness on the Groq wrapper itself); this file focuses on what the *route* does
around that call: authentication, error translation (LLMError -> HTTP 503),
the INSUFFICIENT_DATA flag being stripped from the visible answer, and — most
importantly for a multi-tenant app — that one user's assistant conversation
never leaks into another user's history.
"""

from unittest.mock import patch

from app.services.llm import LLMError


def test_ask_assistant_requires_auth(client):
    response = client.post("/assistant/ask", json={"question": "What did I train yesterday?"})
    assert response.status_code == 401


def test_ask_assistant_returns_answer_and_saves_it(client, auth_headers):
    with patch("app.routers.assistant.ask_llm", return_value="You trained legs on 2 August."):
        response = client.post(
            "/assistant/ask", headers=auth_headers, json={"question": "What did I train last?"}
        )

    assert response.status_code == 201
    body = response.json()
    assert body["response"] == "You trained legs on 2 August."
    assert body["insufficient_information_flag"] is False

    history = client.get("/assistant/messages", headers=auth_headers).json()
    assert len(history) == 1
    assert history[0]["question"] == "What did I train last?"


def test_ask_assistant_strips_insufficient_data_marker_and_sets_flag(client, auth_headers):
    with patch(
        "app.routers.assistant.ask_llm",
        return_value="INSUFFICIENT_DATA I don't have enough workouts logged to answer that yet.",
    ):
        response = client.post(
            "/assistant/ask", headers=auth_headers, json={"question": "How is my squat progressing?"}
        )

    assert response.status_code == 201
    body = response.json()
    assert body["insufficient_information_flag"] is True
    assert "INSUFFICIENT_DATA" not in body["response"]


def test_ask_assistant_returns_503_when_llm_is_down(client, auth_headers):
    with patch("app.routers.assistant.ask_llm", side_effect=LLMError("The assistant is busy right now.")):
        response = client.post(
            "/assistant/ask", headers=auth_headers, json={"question": "What did I train last?"}
        )

    assert response.status_code == 503
    assert response.json()["detail"] == "The assistant is busy right now."


def test_failed_assistant_call_is_not_saved_to_history(client, auth_headers):
    with patch("app.routers.assistant.ask_llm", side_effect=LLMError("down")):
        client.post("/assistant/ask", headers=auth_headers, json={"question": "What did I train last?"})

    history = client.get("/assistant/messages", headers=auth_headers).json()
    assert history == []


def test_question_too_short_is_rejected_before_calling_llm(client, auth_headers):
    with patch("app.routers.assistant.ask_llm") as mock_ask:
        response = client.post("/assistant/ask", headers=auth_headers, json={"question": "hi"})

    assert response.status_code == 422  # fails AssistantAsk's min_length=3 validation
    mock_ask.assert_not_called()


def test_assistant_history_is_isolated_per_user(client, auth_headers, other_auth_headers):
    with patch("app.routers.assistant.ask_llm", return_value="answer for user one"):
        client.post("/assistant/ask", headers=auth_headers, json={"question": "What did I train last?"})

    with patch("app.routers.assistant.ask_llm", return_value="answer for user two"):
        client.post("/assistant/ask", headers=other_auth_headers, json={"question": "What did I train last?"})

    user_one_history = client.get("/assistant/messages", headers=auth_headers).json()
    user_two_history = client.get("/assistant/messages", headers=other_auth_headers).json()

    assert len(user_one_history) == 1
    assert len(user_two_history) == 1
    assert user_one_history[0]["response"] == "answer for user one"
    assert user_two_history[0]["response"] == "answer for user two"
