"""
AI-GENERATED FILE
Generated by Claude (Anthropic AI coding assistant), 2026-08-24, for the MSc IT+
Build & Test phase of the Gymora project.

Integration tests for app/routers/workout_log.py: create/list/get/update/delete,
plus the two behaviours that matter most for correctness in a multi-user app:
- ownership isolation (one user must never see or modify another user's data)
- boundary counts (0, 1, many exercises per workout) as recommended in the
  MSc IT+ Build & Test slides ("0, 1, Many - for each module/function/db call")
"""


def test_create_workout_log_requires_auth(client):
    response = client.post("/workouts/", json={"workout_date": "2026-08-01", "exercises": []})
    assert response.status_code == 401


def test_create_workout_log_with_zero_exercises(client, auth_headers):
    response = client.post(
        "/workouts/",
        headers=auth_headers,
        json={"workout_date": "2026-08-01", "title": "Rest day check-in", "exercises": []},
    )

    assert response.status_code == 201
    assert response.json()["exercises"] == []


def test_create_workout_log_with_many_exercises(client, auth_headers, sample_exercise):
    payload = {
        "workout_date": "2026-08-02",
        "title": "Push day",
        "exercises": [
            {"exercise_id": sample_exercise.exercise_id, "sets": 3, "reps": 10, "weight": 40},
            {"exercise_id": sample_exercise.exercise_id, "sets": 4, "reps": 8, "weight": 45},
            {"exercise_id": sample_exercise.exercise_id, "sets": 3, "reps": 12, "weight": 30},
        ],
    }

    response = client.post("/workouts/", headers=auth_headers, json=payload)

    assert response.status_code == 201
    body = response.json()
    assert len(body["exercises"]) == 3
    # exercise_order defaults to loop position (1, 2, 3) when the client doesn't send one
    assert [row["exercise_order"] for row in body["exercises"]] == [1, 2, 3]


def test_create_workout_log_ignores_client_supplied_user_id(client, auth_headers, test_user, other_user):
    # user_id must come from the token, never from the request body,
    # otherwise a user could log a workout under someone else's account.
    response = client.post(
        "/workouts/",
        headers=auth_headers,
        json={"workout_date": "2026-08-01", "user_id": other_user.user_id, "exercises": []},
    )

    assert response.status_code == 201
    assert response.json()["user_id"] == test_user.user_id


def test_list_workout_logs_only_returns_own_logs(client, auth_headers, other_auth_headers):
    client.post("/workouts/", headers=auth_headers, json={"workout_date": "2026-08-01", "exercises": []})
    client.post("/workouts/", headers=other_auth_headers, json={"workout_date": "2026-08-02", "exercises": []})

    response = client.get("/workouts/", headers=auth_headers)

    assert response.status_code == 200
    body = response.json()
    assert len(body) == 1
    assert body[0]["workout_date"] == "2026-08-01"


def test_list_workout_logs_orders_newest_first(client, auth_headers):
    client.post("/workouts/", headers=auth_headers, json={"workout_date": "2026-07-01", "exercises": []})
    client.post("/workouts/", headers=auth_headers, json={"workout_date": "2026-08-01", "exercises": []})

    response = client.get("/workouts/", headers=auth_headers)

    dates = [row["workout_date"] for row in response.json()]
    assert dates == ["2026-08-01", "2026-07-01"]


def test_get_nonexistent_workout_log_returns_404(client, auth_headers):
    response = client.get("/workouts/99999", headers=auth_headers)
    assert response.status_code == 404


def test_get_other_users_workout_log_returns_404_not_403(client, auth_headers, other_auth_headers):
    # 404 (not 403) on purpose, so a user can't tell the difference between
    # "doesn't exist" and "exists but isn't yours" by probing ids.
    created = client.post(
        "/workouts/", headers=other_auth_headers, json={"workout_date": "2026-08-01", "exercises": []}
    ).json()

    response = client.get(f"/workouts/{created['workout_log_id']}", headers=auth_headers)

    assert response.status_code == 404


def test_update_workout_log_only_changes_sent_fields(client, auth_headers):
    created = client.post(
        "/workouts/",
        headers=auth_headers,
        json={"workout_date": "2026-08-01", "title": "Original title", "exercises": []},
    ).json()

    response = client.put(
        f"/workouts/{created['workout_log_id']}",
        headers=auth_headers,
        json={"notes": "Felt strong today"},
    )

    assert response.status_code == 200
    body = response.json()
    assert body["title"] == "Original title"  # untouched
    assert body["notes"] == "Felt strong today"


def test_cannot_update_other_users_workout_log(client, auth_headers, other_auth_headers):
    created = client.post(
        "/workouts/", headers=other_auth_headers, json={"workout_date": "2026-08-01", "exercises": []}
    ).json()

    response = client.put(
        f"/workouts/{created['workout_log_id']}",
        headers=auth_headers,
        json={"notes": "Trying to tamper"},
    )

    assert response.status_code == 404


def test_delete_workout_log_removes_it(client, auth_headers):
    created = client.post(
        "/workouts/", headers=auth_headers, json={"workout_date": "2026-08-01", "exercises": []}
    ).json()
    workout_id = created["workout_log_id"]

    delete_response = client.delete(f"/workouts/{workout_id}", headers=auth_headers)
    assert delete_response.status_code == 204

    get_response = client.get(f"/workouts/{workout_id}", headers=auth_headers)
    assert get_response.status_code == 404


def test_cannot_delete_other_users_workout_log(client, auth_headers, other_auth_headers):
    created = client.post(
        "/workouts/", headers=other_auth_headers, json={"workout_date": "2026-08-01", "exercises": []}
    ).json()

    response = client.delete(f"/workouts/{created['workout_log_id']}", headers=auth_headers)
    assert response.status_code == 404
