"""
AI-GENERATED FILE
Generated by Claude (Anthropic AI coding assistant), 2026-08-24, for the MSc IT+
Build & Test phase of the Gymora project.

Test harness for app/services/llm.py (the Groq API wrapper), matching the "Test
harness" pattern from the MSc IT+ Build & Test slides: rather than calling the
real external API in every test run (slow, costs quota, needs network + a real
key), `requests.post` is replaced with a small local double that returns a
canned response. This is exactly the "#Get Dummy Cloud" pattern from the slides,
applied with unittest.mock instead of a config switch.

These tests specifically target the *failure paths* that ask_llm() already
handles in code but that a normal dev/demo session would rarely trigger on its
own (429 rate limiting, a non-200 response, a malformed body, no network) — the
"most students focus on what's working, not what might fail" point from the slides.
"""

from unittest.mock import patch

import pytest
import requests

from app.services.llm import LLMError, ask_llm


class FakeResponse:
    """A minimal stand-in for requests.Response, carrying only what ask_llm() reads."""

    def __init__(self, status_code, json_body=None, text=""):
        self.status_code = status_code
        self._json_body = json_body if json_body is not None else {}
        self.text = text
        self.ok = 200 <= status_code < 300

    def json(self):
        return self._json_body


def test_ask_llm_returns_message_content_on_success():
    fake_response = FakeResponse(
        200,
        json_body={"choices": [{"message": {"content": "Here is your workout plan."}}]},
    )

    with patch("app.services.llm.requests.post", return_value=fake_response):
        result = ask_llm("system prompt", "user message")

    assert result == "Here is your workout plan."


def test_ask_llm_sends_expected_request_shape():
    fake_response = FakeResponse(200, json_body={"choices": [{"message": {"content": "ok"}}]})

    with patch("app.services.llm.requests.post", return_value=fake_response) as mock_post:
        ask_llm("You are a helpful assistant.", "What should I train today?")

    _, kwargs = mock_post.call_args
    assert kwargs["headers"]["Authorization"].startswith("Bearer ")
    assert kwargs["json"]["messages"] == [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "What should I train today?"},
    ]
    assert kwargs["json"]["temperature"] == 0.3
    assert kwargs["json"]["max_tokens"] == 500
    assert kwargs["timeout"] == 30


def test_ask_llm_raises_llm_error_on_429_rate_limit():
    fake_response = FakeResponse(429)

    with patch("app.services.llm.requests.post", return_value=fake_response):
        with pytest.raises(LLMError, match="busy"):
            ask_llm("system", "user")


def test_ask_llm_raises_llm_error_on_server_error():
    fake_response = FakeResponse(500, text="internal server error")

    with patch("app.services.llm.requests.post", return_value=fake_response):
        with pytest.raises(LLMError):
            ask_llm("system", "user")


def test_ask_llm_raises_llm_error_on_malformed_response_body():
    # 200 OK, but the body doesn't have the "choices" shape ask_llm() expects.
    fake_response = FakeResponse(200, json_body={"unexpected": "shape"})

    with patch("app.services.llm.requests.post", return_value=fake_response):
        with pytest.raises(LLMError, match="unexpected response"):
            ask_llm("system", "user")


def test_ask_llm_raises_llm_error_when_network_fails():
    with patch("app.services.llm.requests.post", side_effect=requests.ConnectionError("no network")):
        with pytest.raises(LLMError, match="Could not reach"):
            ask_llm("system", "user")


def test_ask_llm_raises_llm_error_on_timeout():
    with patch("app.services.llm.requests.post", side_effect=requests.Timeout("timed out")):
        with pytest.raises(LLMError):
            ask_llm("system", "user")
