"""
AI-GENERATED FILE
Generated by Claude (Anthropic AI coding assistant), 2026-08-24, for the MSc IT+
Build & Test phase of the Gymora project.

Unit tests for app/services/routine_generator.py — the "rules" half of routine
generation (as opposed to the LLM half, which only writes the explanation text).
Because generate_routine() is deterministic for a given input, it's a strong
candidate for direct unit testing rather than only testing it through the API.
"""

from types import SimpleNamespace

from app.services.routine_generator import (
    exercises_per_day,
    find_exercises_for_muscle,
    generate_routine,
    get_sets_and_reps,
)


def test_exercises_per_day_picks_the_closest_bracket_not_over_budget():
    assert exercises_per_day(20) == 4  # below the smallest bracket -> falls back to 4
    assert exercises_per_day(30) == 4
    assert exercises_per_day(45) == 5
    assert exercises_per_day(60) == 6
    assert exercises_per_day(90) == 8
    assert exercises_per_day(120) == 8  # above the largest bracket -> stays at the max


def test_get_sets_and_reps_known_goal():
    assert get_sets_and_reps("strength") == {"sets": 4, "reps": "4-6", "rest": 150}


def test_get_sets_and_reps_is_case_and_whitespace_insensitive():
    assert get_sets_and_reps("  Muscle Gain  ") == get_sets_and_reps("muscle gain")


def test_get_sets_and_reps_unknown_goal_falls_back_to_default():
    assert get_sets_and_reps("world domination") == {"sets": 3, "reps": "10-12", "rest": 60}


def test_find_exercises_for_muscle_prefers_primary_tagged_exercises(db_session, exercise_library):
    found = find_exercises_for_muscle(
        db=db_session,
        muscle_name="Chest",
        equipment_names=[],
        experience_level="beginner",
        how_many=5,
        already_used=set(),
    )

    names = {exercise.name for exercise in found}
    assert "Barbell Bench Press" in names
    assert "Dumbbell Fly" in names


def test_find_exercises_for_muscle_respects_equipment_filter(db_session, exercise_library):
    # Only Dumbbell-equipped chest exercises should come back.
    found = find_exercises_for_muscle(
        db=db_session,
        muscle_name="Chest",
        equipment_names=["Dumbbell"],
        experience_level="beginner",
        how_many=5,
        already_used=set(),
    )

    names = {exercise.name for exercise in found}
    assert names == {"Dumbbell Fly"}


def test_find_exercises_for_muscle_excludes_already_used(db_session, exercise_library):
    all_chest = find_exercises_for_muscle(
        db=db_session,
        muscle_name="Chest",
        equipment_names=[],
        experience_level="beginner",
        how_many=5,
        already_used=set(),
    )
    already_used = {all_chest[0].exercise_id}

    remaining = find_exercises_for_muscle(
        db=db_session,
        muscle_name="Chest",
        equipment_names=[],
        experience_level="beginner",
        how_many=5,
        already_used=already_used,
    )

    assert all_chest[0].exercise_id not in {exercise.exercise_id for exercise in remaining}


def test_find_exercises_for_muscle_returns_nothing_for_unknown_muscle(db_session, exercise_library):
    found = find_exercises_for_muscle(
        db=db_session,
        muscle_name="Forearms",  # not seeded in the exercise_library fixture
        equipment_names=[],
        experience_level="beginner",
        how_many=5,
        already_used=set(),
    )
    assert found == []


def test_generate_routine_never_repeats_an_exercise_across_days(db_session, exercise_library):
    request = SimpleNamespace(
        goal="strength",
        experience_level="beginner",
        days_per_week=3,
        session_length_minutes=45,
        equipment=[],
    )

    plan = generate_routine(db_session, request)

    exercise_ids = [item["exercise"].exercise_id for item in plan]
    assert len(exercise_ids) == len(set(exercise_ids))


def test_generate_routine_spans_the_requested_number_of_days(db_session, exercise_library):
    request = SimpleNamespace(
        goal="strength",
        experience_level="beginner",
        days_per_week=3,
        session_length_minutes=45,
        equipment=[],
    )

    plan = generate_routine(db_session, request)

    day_numbers = {item["day_number"] for item in plan}
    assert day_numbers <= {1, 2, 3}
    assert 1 in day_numbers


def test_generate_routine_returns_empty_plan_when_library_is_empty(db_session):
    request = SimpleNamespace(
        goal="strength",
        experience_level="beginner",
        days_per_week=3,
        session_length_minutes=45,
        equipment=[],
    )

    plan = generate_routine(db_session, request)
    assert plan == []
