"""
AI-GENERATED FILE
Generated by Claude (Anthropic AI coding assistant), 2026-08-24, for the MSc IT+
Build & Test phase of the Gymora project.

Unit tests for app/core/security.py — password hashing and JWT creation/decoding.
These replace the old manual scratch scripts (backend/test_hash.py, test_token.py),
which only printed output for a human to eyeball rather than asserting anything.
"""

from datetime import datetime, timedelta, timezone

import jwt
import pytest

from app.config import get_settings
from app.core.security import (
    create_access_token,
    decode_access_token,
    hash_password,
    verify_password,
)


def test_hash_password_does_not_store_plaintext():
    hashed = hash_password("hunter2")
    assert hashed != "hunter2"


def test_verify_password_accepts_correct_password():
    hashed = hash_password("hunter2")
    assert verify_password("hunter2", hashed) is True


def test_verify_password_rejects_wrong_password():
    hashed = hash_password("hunter2")
    assert verify_password("wrong-password", hashed) is False


def test_hash_password_uses_a_random_salt():
    # Same input, hashed twice, must not produce the same hash — otherwise
    # two users with the same password would be trivially identifiable/crackable
    # from the database alone.
    first = hash_password("hunter2")
    second = hash_password("hunter2")
    assert first != second


def test_create_and_decode_access_token_round_trip():
    token = create_access_token(user_id=42)
    assert decode_access_token(token) == 42


def test_decode_access_token_rejects_tampered_token():
    token = create_access_token(user_id=42)
    tampered = token[:-1] + ("A" if token[-1] != "A" else "B")
    assert decode_access_token(tampered) is None


def test_decode_access_token_rejects_wrong_signing_key():
    settings = get_settings()
    payload = {
        "sub": "42",
        "exp": datetime.now(timezone.utc) + timedelta(minutes=30),
    }
    token = jwt.encode(payload, "a-completely-different-key", algorithm=settings.jwt_algorithm)
    assert decode_access_token(token) is None


def test_decode_access_token_rejects_expired_token():
    settings = get_settings()
    payload = {
        "sub": "42",
        "exp": datetime.now(timezone.utc) - timedelta(minutes=1),
    }
    token = jwt.encode(payload, settings.jwt_secret_key, algorithm=settings.jwt_algorithm)
    assert decode_access_token(token) is None


def test_decode_access_token_rejects_token_missing_subject():
    settings = get_settings()
    payload = {"exp": datetime.now(timezone.utc) + timedelta(minutes=30)}
    token = jwt.encode(payload, settings.jwt_secret_key, algorithm=settings.jwt_algorithm)
    assert decode_access_token(token) is None


def test_decode_access_token_rejects_garbage_string():
    assert decode_access_token("not-a-real-token") is None
