// AI-GENERATED FILE
// Generated by Claude (Anthropic AI coding assistant), 2026-08-24, for the MSc IT+
// Build & Test phase of the Gymora project.
//
// Unit tests for src/api/client.js. `global.fetch` is replaced with a mock for
// every test (no real network calls), matching the MSc IT+ Build & Test slides'
// "test harness" idea applied to a browser-side API client instead of a server-side one.
// Covers: token storage, the two request-body formats (JSON vs form-encoded for
// the OAuth2 /auth/token endpoint), and the error-message extraction logic in
// apiPostAuth, which has three different branches depending on what the server sends back.

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import {
  apiDeleteAuth,
  apiGetAuth,
  apiPostAuth,
  clearToken,
  getToken,
  login,
  register,
  saveToken,
} from './client.js'

function jsonResponse(body, { ok = true, status = 200 } = {}) {
  return {
    ok,
    status,
    json: () => Promise.resolve(body),
  }
}

beforeEach(() => {
  localStorage.clear()
  global.fetch = vi.fn()
})

afterEach(() => {
  vi.restoreAllMocks()
})

describe('token storage', () => {
  it('saveToken/getToken/clearToken round-trip through localStorage', () => {
    expect(getToken()).toBeNull()

    saveToken('abc.def.ghi')
    expect(getToken()).toBe('abc.def.ghi')

    clearToken()
    expect(getToken()).toBeNull()
  })
})

describe('login', () => {
  it('sends form-encoded credentials to /auth/token and saves the returned token', async () => {
    global.fetch.mockResolvedValueOnce(
      jsonResponse({ access_token: 'a-real-token', token_type: 'bearer' })
    )

    const result = await login('user@example.com', 'hunter2')

    expect(global.fetch).toHaveBeenCalledOnce()
    const [url, options] = global.fetch.mock.calls[0]
    expect(url).toContain('/auth/token')
    expect(options.headers['Content-Type']).toBe('application/x-www-form-urlencoded')
    expect(options.body.toString()).toContain('username=user%40example.com')

    expect(result.access_token).toBe('a-real-token')
    expect(getToken()).toBe('a-real-token')
  })

  it('throws a generic message and does not store a token on failure', async () => {
    global.fetch.mockResolvedValueOnce(jsonResponse({}, { ok: false, status: 401 }))

    await expect(login('user@example.com', 'wrong')).rejects.toThrow(
      'Incorrect email or password'
    )
    expect(getToken()).toBeNull()
  })
})

describe('register', () => {
  it('sends JSON and returns the created user on success', async () => {
    const createdUser = { user_id: 1, username: 'newuser', email: 'new@example.com' }
    global.fetch.mockResolvedValueOnce(jsonResponse(createdUser))

    const result = await register('newuser', 'new@example.com', 'Password123!')

    const [, options] = global.fetch.mock.calls[0]
    expect(options.headers['Content-Type']).toBe('application/json')
    expect(JSON.parse(options.body)).toEqual({
      username: 'newuser',
      email: 'new@example.com',
      password: 'Password123!',
    })
    expect(result).toEqual(createdUser)
  })

  it('surfaces the backend detail message on failure (e.g. duplicate email)', async () => {
    global.fetch.mockResolvedValueOnce(
      jsonResponse({ detail: 'Email already registered' }, { ok: false, status: 400 })
    )

    await expect(register('u', 'dupe@example.com', 'pw')).rejects.toThrow(
      'Email already registered'
    )
  })
})

describe('apiGetAuth', () => {
  it('attaches the stored token as a Bearer header', async () => {
    saveToken('my-token')
    global.fetch.mockResolvedValueOnce(jsonResponse({ ok: true }))

    await apiGetAuth('/workouts/')

    const [, options] = global.fetch.mock.calls[0]
    expect(options.headers.Authorization).toBe('Bearer my-token')
  })

  it('throws on a non-ok response', async () => {
    global.fetch.mockResolvedValueOnce(jsonResponse({}, { ok: false, status: 404 }))

    await expect(apiGetAuth('/workouts/999')).rejects.toThrow('Request failed: 404')
  })
})

describe('apiPostAuth error message extraction', () => {
  it('uses the string detail from a validation error response', async () => {
    global.fetch.mockResolvedValueOnce(
      jsonResponse({ detail: 'Workout log not found' }, { ok: false, status: 404 })
    )

    await expect(apiPostAuth('/workouts/', {})).rejects.toThrow('Workout log not found')
  })

  it('replaces an array-shaped FastAPI validation detail with a friendly message', async () => {
    global.fetch.mockResolvedValueOnce(
      jsonResponse(
        { detail: [{ loc: ['body', 'workout_date'], msg: 'field required' }] },
        { ok: false, status: 422 }
      )
    )

    await expect(apiPostAuth('/workouts/', {})).rejects.toThrow(
      'Some fields were invalid. Please check the form.'
    )
  })

  it('falls back to a generic message when the error body is not JSON', async () => {
    global.fetch.mockResolvedValueOnce({
      ok: false,
      status: 500,
      json: () => Promise.reject(new Error('not json')),
    })

    await expect(apiPostAuth('/workouts/', {})).rejects.toThrow('Request failed: 500')
  })
})

describe('apiDeleteAuth', () => {
  it('returns null on a successful 204 response instead of parsing a body', async () => {
    global.fetch.mockResolvedValueOnce({ ok: true, status: 204 })

    const result = await apiDeleteAuth('/routines/1')
    expect(result).toBeNull()
  })
})
