// AI-GENERATED FILE
// Generated by Claude (Anthropic AI coding assistant), 2026-08-24, for the MSc IT+
// Build & Test phase of the Gymora project.
//
// Unit tests for the Login page. Like ProtectedRoute.test.jsx, useAuth() is
// mocked so these tests exercise the form's own logic (submit handling, error
// display, disabling the button while a request is in flight) without depending
// on the real API client or a running backend.

import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import Login from './Login.jsx'
import { useAuth } from '../context/AuthContext.jsx'

vi.mock('../context/AuthContext.jsx', () => ({
  useAuth: vi.fn(),
}))

const mockNavigate = vi.fn()
vi.mock('react-router-dom', async () => {
  const actual = await vi.importActual('react-router-dom')
  return { ...actual, useNavigate: () => mockNavigate }
})

function renderLogin() {
  return render(
    <MemoryRouter>
      <Login />
    </MemoryRouter>
  )
}

beforeEach(() => {
  mockNavigate.mockClear()
})

describe('Login page', () => {
  it('logs in and navigates home on successful submit', async () => {
    const login = vi.fn().mockResolvedValue({ access_token: 'token' })
    useAuth.mockReturnValue({ login })
    const user = userEvent.setup()

    renderLogin()

    await user.type(screen.getByLabelText(/email address/i), 'test@example.com')
    await user.type(screen.getByLabelText(/password/i), 'Password123!')
    await user.click(screen.getByRole('button', { name: /log in/i }))

    await waitFor(() => expect(login).toHaveBeenCalledWith('test@example.com', 'Password123!'))
    expect(mockNavigate).toHaveBeenCalledWith('/')
  })

  it('shows the error message and does not navigate on failed login', async () => {
    const login = vi.fn().mockRejectedValue(new Error('Incorrect email or password'))
    useAuth.mockReturnValue({ login })
    const user = userEvent.setup()

    renderLogin()

    await user.type(screen.getByLabelText(/email address/i), 'test@example.com')
    await user.type(screen.getByLabelText(/password/i), 'wrong-password')
    await user.click(screen.getByRole('button', { name: /log in/i }))

    expect(await screen.findByText('Incorrect email or password')).toBeInTheDocument()
    expect(mockNavigate).not.toHaveBeenCalled()
  })

  it('disables the submit button while the request is in flight', async () => {
    let resolveLogin
    const login = vi.fn(
      () =>
        new Promise((resolve) => {
          resolveLogin = resolve
        })
    )
    useAuth.mockReturnValue({ login })
    const user = userEvent.setup()

    renderLogin()

    await user.type(screen.getByLabelText(/email address/i), 'test@example.com')
    await user.type(screen.getByLabelText(/password/i), 'Password123!')
    await user.click(screen.getByRole('button', { name: /log in/i }))

    expect(screen.getByRole('button', { name: /logging in/i })).toBeDisabled()

    resolveLogin({ access_token: 'token' })
    await waitFor(() => expect(mockNavigate).toHaveBeenCalled())
  })
})
