// AI-GENERATED FILE
// Generated by Claude (Anthropic AI coding assistant), 2026-08-24, for the MSc IT+
// Build & Test phase of the Gymora project.
//
// Runs before every Vitest test file. Adds the jest-dom matchers
// (toBeInTheDocument, toHaveTextContent, etc.) used across the frontend tests.

import '@testing-library/jest-dom'
