"""create tables

Revision ID: 5234aeb81644
Revises: 5c58dffd9aed
Create Date: 2026-07-20 21:58:12.213386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5234aeb81644'
down_revision: Union[str, Sequence[str], None] = '5c58dffd9aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('context_used', sa.Text(), nullable=True),
    sa.Column('insufficient_information_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('routine',
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('goal', sa.String(length=100), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('target_muscle_group_id', sa.Integer(), nullable=True),
    sa.Column('days_per_week', sa.Integer(), nullable=True),
    sa.Column('session_length_minutes', sa.Integer(), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['target_muscle_group_id'], ['muscle_groups.muscle_group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('routine_id')
    )
    op.create_table('workout_log',
    sa.Column('workout_log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('workout_log_id')
    )
    op.create_table('routine_exercise',
    sa.Column('routine_exercise_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('exercise_order', sa.Integer(), nullable=True),
    sa.Column('suggested_sets', sa.Integer(), nullable=True),
    sa.Column('suggested_reps', sa.String(length=50), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.routine_id'], ),
    sa.PrimaryKeyConstraint('routine_exercise_id')
    )
    op.create_table('workout_log_exercise',
    sa.Column('workout_log_exercise_id', sa.Integer(), nullable=False),
    sa.Column('workout_log_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('exercise_order', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ),
    sa.ForeignKeyConstraint(['workout_log_id'], ['workout_log.workout_log_id'], ),
    sa.PrimaryKeyConstraint('workout_log_exercise_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_log_exercise')
    op.drop_table('routine_exercise')
    op.drop_table('workout_log')
    op.drop_table('routine')
    op.drop_table('assistant_message')
    # ### end Alembic commands ###
