"""created ExerciseMuscleGroup and ExerciseEquipment

Revision ID: 5c58dffd9aed
Revises: 61cf083c7602
Create Date: 2026-07-20 21:28:20.598508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c58dffd9aed'
down_revision: Union[str, Sequence[str], None] = '61cf083c7602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_equipment',
    sa.Column('exercise_equipment_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ),
    sa.PrimaryKeyConstraint('exercise_equipment_id')
    )
    op.create_table('exercise_muscle_group',
    sa.Column('exercise_muscle_group_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_groups.muscle_group_id'], ),
    sa.PrimaryKeyConstraint('exercise_muscle_group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_muscle_group')
    op.drop_table('exercise_equipment')
    # ### end Alembic commands ###
